### ISSUE TITLE
Add database feature

### ISSUE THREAD

**Issue by litan1106** [sherifabdlnaby/symdocker#3]
Real world app always have a database.

**Comment by hacfi** [comment]
As you copy the `docker-compose.yml` to your project you can add your database of choice there. For `mysql` e.g.:

```
version: '3.4'

services:
  # ...

  db:
    image: mysql:5.7 # or percona or mariadb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql:rw
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  mysql_data:
    driver: local
```

and add `DATABASE_URL: "mysql://user:password@db:3306/db"` to your env vars (see https://github.com/sherifabdlnaby/symdocker/blob/master/docker/.compose/docker-compose.yml#L14).

For `postgres` you can use something like:

```
version: '3.4'

services:
  # ...

  db:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "db"

volumes:
  pgdata:
    driver: local
```

and use `"postgres://user:password@db:5432/db"` as the `DATABASE_URL`.
